// ReSharper disable InconsistentNaming
using System.Collections.Generic;
        
public static class Defines {
    public static class Build {
        public static bool Include_update = true;
        public static string Name = @"dragon";
    }
    public static class Config {
        public static string Auto_voice = @"audio/voice/{id}.ogg";
        public static List<string> Layers = new List<string> { "master0", "master", "background", "middle", "forward", "transient", "screens", "overlay" };
        public static class Mouse {
            public static List<object> Default = new List<object>();
        }
        public static string Name = @"_(""灾厄黑龙与谎言公主"")";
        public static string Version = @"1.0";
        public static bool Has_sound = true;
        public static bool Has_music = true;
        public static bool Has_voice = true;
        public static float Default_music_volume = 0.45f;
        public static float Default_sfx_volume = 0.8f;
        public static int Default_voice_volume = 1;
        public static string Main_menu_music = @"audio/music/adventure.mp3";
        public static string Enter_transition = @"Dissolve(0.5)";
        public static string Exit_transition = @"Dissolve(0.5)";
        public static string Intra_transition = @"Dissolve(0.5)";
        public static object After_load_transition = null;
        public static object End_game_transition = null;
        public static string Window = @"auto";
        public static string Window_show_transition = @"Dissolve(.2)";
        public static string Window_hide_transition = @"Dissolve(.2)";
        public static string Save_directory = @"dragon-1703771187";
        public static string Window_icon = @"gui/window_icon.png";
        public static bool Has_quicksave = false;
        public static string Nvl_list_length = @"gui.nvl_list_length";
        public static bool Check_conflicting_properties = true;
        public static int Thumbnail_width = 256;
        public static int Thumbnail_height = 144;
        public static int History_length = 50;
    }
    public static class Gui {
        public static int Nvl_height = 115;
        public static bool Show_name = false;
        public static string About = @"_p(""""""  """""")";
        public static List<string> History_allow_tags = new List<string> { "alt", "rt", "rb", "noalt", "art" };
        public static string Accent_color = @"#cc0000";
        public static string Idle_color = @"#FFFFFF";
        public static string Idle_small_color = @"#aaaaaa";
        public static string Hover_color = @"#e06666";
        public static string Selected_color = @"#ffffff";
        public static string Insensitive_color = @"#8888887f";
        public static string Muted_color = @"#510000";
        public static string Hover_muted_color = @"#7a0000";
        public static string Text_color = @"#ffffff";
        public static string Interface_text_color = @"#ffffff";
        public static string Text_font = @"GenSenRounded-M.ttc";
        public static string Name_text_font = @"GenSenRounded-M.ttc";
        public static string Interface_text_font = @"GenSenRounded-M.ttc";
        public static int Text_size = 22;
        public static int Name_text_size = 30;
        public static int Interface_text_size = 22;
        public static int Label_text_size = 24;
        public static int Notify_text_size = 16;
        public static int Title_text_size = 50;
        public static string Main_menu_background = @"gui/main_menu.png";
        public static string Game_menu_background = @"gui/game_menu.png";
        public static int Textbox_height = 230;
        public static float Textbox_yalign = 1.0f;
        public static int Name_xpos = 322;
        public static int Name_ypos = 7;
        public static float Name_xalign = 0.0f;
        public static object Namebox_width = null;
        public static object Namebox_height = null;
        public static string Namebox_borders = @"Borders(5, 5, 5, 5)";
        public static bool Namebox_tile = false;
        public static int Dialogue_xpos = 340;
        public static int Dialogue_ypos = 80;
        public static int Dialogue_width = 700;
        public static float Dialogue_text_xalign = 0.0f;
        public static object Button_width = null;
        public static object Button_height = null;
        public static string Button_borders = @"Borders(4, 4, 4, 4)";
        public static bool Button_tile = false;
        public static string Button_text_font = @"gui.interface_text_font";
        public static string Button_text_size = @"gui.interface_text_size";
        public static string Button_text_idle_color = @"gui.idle_color";
        public static string Button_text_hover_color = @"gui.hover_color";
        public static string Button_text_selected_color = @"gui.selected_color";
        public static string Button_text_insensitive_color = @"gui.insensitive_color";
        public static float Button_text_xalign = 0.0f;
        public static string Radio_button_borders = @"Borders(18, 4, 4, 4)";
        public static string Check_button_borders = @"Borders(18, 4, 4, 4)";
        public static float Confirm_button_text_xalign = 0.5f;
        public static string Page_button_borders = @"Borders(10, 4, 10, 4)";
        public static string Quick_button_borders = @"Borders(10, 4, 10, 0)";
        public static int Quick_button_text_size = 14;
        public static string Quick_button_text_idle_color = @"gui.idle_small_color";
        public static string Quick_button_text_selected_color = @"gui.accent_color";
        public static int Choice_button_width = 790;
        public static object Choice_button_height = null;
        public static bool Choice_button_tile = false;
        public static string Choice_button_borders = @"Borders(100, 5, 100, 5)";
        public static string Choice_button_text_font = @"gui.text_font";
        public static string Choice_button_text_size = @"gui.text_size";
        public static int Choice_button_text_xalign = 0;
        public static string Choice_button_text_idle_color = @"#888888";
        public static string Choice_button_text_hover_color = @"#ffffff";
        public static string Choice_button_text_insensitive_color = @"#8888887f";
        public static int Slot_button_width = 276;
        public static int Slot_button_height = 206;
        public static string Slot_button_borders = @"Borders(10, 10, 10, 10)";
        public static int Slot_button_text_size = 14;
        public static float Slot_button_text_xalign = 0.5f;
        public static string Slot_button_text_idle_color = @"gui.idle_small_color";
        public static string Slot_button_text_selected_idle_color = @"gui.selected_color";
        public static string Slot_button_text_selected_hover_color = @"gui.hover_color";
        public static int File_slot_cols = 3;
        public static int File_slot_rows = 2;
        public static int Navigation_xpos = 40;
        public static int Skip_ypos = 10;
        public static int Notify_ypos = 45;
        public static int Choice_spacing = -20;
        public static int Navigation_spacing = 4;
        public static int Pref_spacing = 10;
        public static int Pref_button_spacing = 0;
        public static int Page_spacing = 0;
        public static int Slot_spacing = 10;
        public static float Main_menu_text_xalign = 1.0f;
        public static string Frame_borders = @"Borders(4, 4, 4, 4)";
        public static string Confirm_frame_borders = @"Borders(40, 40, 40, 40)";
        public static string Skip_frame_borders = @"Borders(16, 5, 50, 5)";
        public static string Notify_frame_borders = @"Borders(16, 5, 40, 5)";
        public static bool Frame_tile = false;
        public static int Bar_size = 25;
        public static int Scrollbar_size = 12;
        public static int Slider_size = 25;
        public static bool Bar_tile = false;
        public static bool Scrollbar_tile = false;
        public static bool Slider_tile = false;
        public static string Bar_borders = @"Borders(4, 4, 4, 4)";
        public static string Scrollbar_borders = @"Borders(4, 4, 4, 4)";
        public static string Slider_borders = @"Borders(4, 4, 4, 4)";
        public static string Vbar_borders = @"Borders(4, 4, 4, 4)";
        public static string Vscrollbar_borders = @"Borders(4, 4, 4, 4)";
        public static string Vslider_borders = @"Borders(4, 4, 4, 4)";
        public static string Unscrollable = @"hide";
        public static int History_height = 140;
        public static int History_name_xpos = 155;
        public static int History_name_ypos = 0;
        public static int History_name_width = 155;
        public static float History_name_xalign = 1.0f;
        public static int History_text_xpos = 170;
        public static int History_text_ypos = 2;
        public static int History_text_width = 740;
        public static float History_text_xalign = 0.0f;
        public static string Nvl_borders = @"Borders(0, 10, 0, 20)";
        public static int Nvl_list_length = 6;
        public static int Nvl_spacing = 10;
        public static int Nvl_name_xpos = 430;
        public static int Nvl_name_ypos = 0;
        public static int Nvl_name_width = 150;
        public static float Nvl_name_xalign = 1.0f;
        public static int Nvl_text_xpos = 450;
        public static int Nvl_text_ypos = 8;
        public static int Nvl_text_width = 590;
        public static float Nvl_text_xalign = 0.0f;
        public static int Nvl_thought_xpos = 240;
        public static int Nvl_thought_ypos = 0;
        public static int Nvl_thought_width = 780;
        public static float Nvl_thought_xalign = 0.0f;
        public static int Nvl_button_xpos = 450;
        public static float Nvl_button_xalign = 0.0f;
        public static string Language = @"unicode";
    }
    public static string Nv = @"Character(""[persistent.povname]"",image = ""someone"")";
    public static string Nv1 = @"Character(""[persistent.povname]"", image = ""someone"", what_prefix=""「"",what_suffix=""」"")";
    public static string Nv1_qian = @"Character(""[persistent.povname]"", image = ""someone"")";
    public static string Nv2 = @"Character(""[persistent.povname]"", what_prefix=""「"",what_suffix=""」"")";
    public static string Nv2_qian = @"Character(""[persistent.povname]"")";
    public static string Nv_pangbai_nvl = @"Character( kind=nvl)";
    public static string Nv_pangbai1 = @"Character(""[persistent.povname]"")";
    public static string Nv_pangbai = @"Character(image = ""someone"")";
    public static string Nv_w = @"Character(""[persistent.povname]"",image = ""someone_2"")";
    public static string He = @"Character(""赫泽尔"",voice_tag=""he_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string He_pangbai = @"Character(voice_tag=""he_test"")";
    public static string Nv_pangbai11 = @"Character(image=""someone"",voice_tag=""he_test"")";
    public static string He_qian = @"Character(""赫泽尔"",voice_tag=""he_test"")";
    public static string He_nv = @"Character(""赫泽尔"",voice_tag=""he_test"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string He_nv_qian = @"Character(""赫泽尔"",voice_tag=""he_test"",image=""someone"")";
    public static string He_weizhi_nv = @"Character(""？？？"",voice_tag=""he_test"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string He_weizhi = @"Character(""？？？"",voice_tag=""he_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string He_weizhi_nv_qian = @"Character(""？？？"",voice_tag=""he_test"",image=""someone"")";
    public static string He_heilong = @"Character(""黑龙"",voice_tag=""he_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string He_heilong_nv = @"Character(""黑龙"",voice_tag=""he_test"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string Nuo_2 = @"Character(""诺伯拉"",voice_tag=""nuo_test"",image=""someone_nuo"",what_prefix=""「"",what_suffix=""」"")";
    public static string Nuo_2_qian = @"Character(""诺伯拉"",voice_tag=""nuo_test"",image=""someone_nuo"")";
    public static string Nuo = @"Character(""诺伯拉"",voice_tag=""nuo_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string Nuo_qian = @"Character(""诺伯拉"",voice_tag=""nuo_test"")";
    public static string Nuo_nv = @"Character(""诺伯拉"",voice_tag=""nuo_test"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string Nuo_nv_qian = @"Character(""诺伯拉"",voice_tag=""nuo_test"",image=""someone"")";
    public static string Nuo_weizhi = @"Character(""？？？"",voice_tag=""nuo_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string Nuo_nv_weizhi = @"Character( ""？？？"",image=""someone"",voice_tag=""nuo_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string Nuo_weizhi_qian = @"Character(""？？？"",voice_tag=""nuo_test"")";
    public static string Nuo_weizhi_nv = @"Character(""？？？"",voice_tag=""nuo_test"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string Nuo_weizhi_nv_qian = @"Character(""？？？"",voice_tag=""nuo_test"",image=""someone"")";
    public static string Nuo_1_xin_qian = @"Character(""[persistent.povname]"", image=""someone"", voice_tag=""nuo_test"",window_background = ""textbox_xin_yoffset"",screen = ""say1"")";
    public static string Nuo_1_xin = @"Character(""[persistent.povname]"", image=""someone"", voice_tag=""nuo_test"",what_prefix=""「"",what_suffix=""」"",window_background = ""textbox_xin_yoffset"",screen = ""say1"")";
    public static string Nuo_1_xin_wu = @"Character(""[persistent.povname]"", image=""someone"", voice_tag=""nuo_test"",window_background = ""textbox_xin_yoffset"",screen = ""say1"")";
    public static string Nuo_1_xin_pangbai = @"Character(image=""someone"", voice_tag=""nuo_test"",window_background = ""textbox_xin0_yoffset"",screen = ""say1"")";
    public static string Nuo_1_xin_pangbai1 = @"Character(voice_tag=""nuo_test"",window_background = ""textbox_xin0_yoffset"",screen = ""say1"")";
    public static string Nuo_1_xin_nuo_qian = @"Character(""诺伯拉"", image=""someone"", voice_tag=""nuo_test"",window_background = ""textbox_xin1_yoffset"", screen = ""say2"")";
    public static string Nuo_1_xin_nuo = @"Character(""诺伯拉"", image=""someone"", voice_tag=""nuo_test"",what_prefix=""「"",what_suffix=""」"",window_background = ""textbox_xin1_yoffset"", screen = ""say2"")";
    public static string Nuo_1_xin_nuo1 = @"Character(""诺伯拉"", voice_tag=""nuo_test"",what_prefix=""「"",what_suffix=""」"",window_background = ""textbox_xin1_yoffset"", screen = ""say2"")";
    public static string Nuo_1_xin_nuo1_qian = @"Character(""诺伯拉"", voice_tag=""nuo_test"",window_background = ""textbox_xin1_yoffset"", screen = ""say2"")";
    public static string Nuo_1_xin_nuo_wen = @"Character(""？？？"", image=""someone"", voice_tag=""nuo_test"",what_prefix=""「"",what_suffix=""」"",window_background = ""textbox_xin1_yoffset"", screen = ""say2"")";
    public static string An = @"Character(""安德鲁"",voice_tag=""an_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string An_qian = @"Character(""安德鲁"",voice_tag=""an_test"")";
    public static string An_weizhi = @"Character(""？？？"",voice_tag=""an_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string An_nv = @"Character(""安德鲁"",voice_tag=""an_test"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string An_nv_qian = @"Character(""安德鲁"",voice_tag=""an_test"",image=""someone"")";
    public static string An_1 = @"Character(""安&%鲁"",voice_tag=""an_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string An_2 = @"Character(""洝&%魯#"",voice_tag=""an_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string An_luo = @"Character(""安德鲁·洛恩"",voice_tag=""an_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string An_luo_qian = @"Character(""安德鲁·洛恩"",voice_tag=""an_test"")";
    public static string An_luo_nv = @"Character(""安德鲁·洛恩"",image=""someone"",voice_tag=""an_test"",what_prefix=""「"",what_suffix=""」"")";
    public static string Luo = @"Character(""洛恩"",voice_tag=""luo"",what_prefix=""「"",what_suffix=""」"")";
    public static string Luo_qian = @"Character(""洛恩"",voice_tag=""luo"")";
    public static string Luo_weizhi = @"Character(""？？"",voice_tag=""luo"",what_prefix=""「"",what_suffix=""」"")";
    public static string Luo_nv_weizhi = @"Character(""？？"",image=""someone"",voice_tag=""luo"",what_prefix=""「"",what_suffix=""」"")";
    public static string Luo_nv = @"Character(""洛恩"",voice_tag=""luo"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string Luo_nv_qian = @"Character(""洛恩"",voice_tag=""luo"",image=""someone"")";
    public static string Yao = @"Character(""妖精商人"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Yao_nv = @"Character(""妖精商人"",image=""someone"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Yao_nv_qian = @"Character(""妖精商人"",image=""someone"",voice_tag=""others"")";
    public static string Yao_qian = @"Character(""妖精商人"",voice_tag=""others"")";
    public static string Yao_weizhi = @"Character(""？？？？"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Yao_nv_weizhi = @"Character(""？？？？"",image=""someone"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string A = @"Character(""国王"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string A_nv = @"Character(""国王"",voice_tag=""others"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string B = @"Character(""王后"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string B_nv = @"Character(""王后"",voice_tag=""others"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string C = @"Character(""公主"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string C_qian = @"Character(""公主"",voice_tag=""others"")";
    public static string C_weizhi = @"Character(""? ?"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string C_nv = @"Character(""公主"",voice_tag=""others"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string D = @"Character(""母亲"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string D_nv = @"Character(""母亲"",voice_tag=""others"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string E = @"Character(""医师"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string E_nv = @"Character(""医师"",voice_tag=""others"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string E_weizhi = @"Character(""？？"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string F = @"Character(""小女孩"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string G = @"Character(""神父"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string H = @"Character(""水果摊摊主"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string H_nv = @"Character(""水果摊摊主"",image=""someone"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string I = @"Character(""中年男人店主"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string I_nv = @"Character(""中年男人店主"",image=""someone"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string J = @"Character(""女性店主"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string J_nv = @"Character(""女性店主"",voice_tag=""others"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string Qigai_weizhi = @"Character(""？？？"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string K = @"Character(""法师塔贤者"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string L = @"Character(""高个子骑士"",voice_tag=""others"",image = ""npc_qishi1_zoom"", hat_prefix=""「"",what_suffix=""」"")";
    public static string M = @"Character(""中等骑士"",voice_tag=""others"",image = ""npc_qishi1_zoom"",what_prefix=""「"",what_suffix=""」"")";
    public static string N = @"Character(""骑士"",voice_tag=""others"",image = ""npc_qishi1_zoom"",what_prefix=""「"",what_suffix=""」"")";
    public static string O = @"Character(""骑士团团长"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string P = @"Character(""男性骑士"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string P_qian = @"Character(""男性骑士"",voice_tag=""others"")";
    public static string Q = @"Character(""女骑士"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Q1 = @"Character(""席亚"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string R = @"Character(""卫兵"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string S = @"Character(""菲珀斯"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string S_qian = @"Character(""菲珀斯"",voice_tag=""others"")";
    public static string S_wen = @"Character(""？？？"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string T = @"Character(""教皇"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string U = @"Character(""孩子"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string V = @"Character(""平民"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string W = @"Character(""民众"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string X = @"Character(""年轻摊主"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string X_qian = @"Character(""年轻摊主"",voice_tag=""others"")";
    public static string X_nv = @"Character(""年轻摊主"",voice_tag=""others"",image=""someone"",what_prefix=""「"",what_suffix=""」"")";
    public static string Y = @"Character(""小男孩"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Y_qian = @"Character(""小男孩"",voice_tag=""others"")";
    public static string Z = @"Character(""温和的男声"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Z_qian = @"Character(""温和的男声"",voice_tag=""others"")";
    public static string Bb = @"Character(""银发少年"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Bb_qian = @"Character(""银发少年"",voice_tag=""others"")";
    public static string Bb_1 = @"Character(""？？？"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Bb_2 = @"Character(""微服私访的王子"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Bb_2_qian = @"Character(""微服私访的王子"",voice_tag=""others"")";
    public static string Bb_3 = @"Character(""王子"",voice_tag=""others"",what_prefix=""「"",what_suffix=""」"")";
    public static string Bb_3_qian = @"Character(""王子"",voice_tag=""others"")";
    public static string Wu_nv = @"Character(""[persistent.povname]"",image = ""someone_1"")";
    public static string Wu_nv1 = @"Character(""[persistent.povname]"", image = ""someone_1"", what_prefix=""「"",what_suffix=""」"")";
    public static string Wu_nv_pangbai = @"Character(image = ""someone_1"")";
    public static string Wu_a_nv = @"Character(""国王"",voice_tag=""others"",image=""someone_1"",what_prefix=""「"",what_suffix=""」"")";
    public static string Wu_b_nv = @"Character(""王后"",voice_tag=""others"",image=""someone_1"",what_prefix=""「"",what_suffix=""」"")";
    public static string Wu_c_nv = @"Character(""公主"",voice_tag=""others"",image=""someone_1"",what_prefix=""「"",what_suffix=""」"")";
    public static class Bubble {
        public static string Frame = @"Frame(""gui/bubble.png"", 55, 55, 55, 95)";
        public static string Thoughtframe = @"Frame(""gui/thoughtbubble.png"", 55, 55, 55, 55)";
        public static class Properties {
            public static class Bottom_left {
                public static string Window_background = @"Transform(bubble.frame, xzoom=1, yzoom=1)";
                public static int Window_bottom_padding = 27;
            }
            public static class Bottom_right {
                public static string Window_background = @"Transform(bubble.frame, xzoom=-1, yzoom=1)";
                public static int Window_bottom_padding = 27;
            }
            public static class Top_left {
                public static string Window_background = @"Transform(bubble.frame, xzoom=1, yzoom=-1)";
                public static int Window_top_padding = 27;
            }
            public static class Top_right {
                public static string Window_background = @"Transform(bubble.frame, xzoom=-1, yzoom=-1)";
                public static int Window_top_padding = 27;
            }
            public static class Thought {
                public static string Window_background = @"bubble.thoughtframe";
            }
        }
        public static class Expand_area {
            public static List<int> Bottom_left = new List<int> { 0, 0, 0, 22 };
            public static List<int> Bottom_right = new List<int> { 0, 0, 0, 22 };
            public static List<int> Top_left = new List<int> { 0, 22, 0, 0 };
            public static List<int> Top_right = new List<int> { 0, 22, 0, 0 };
            public static List<int> Thought = new List<int> { 0, 0, 0, 0 };
        }
    }
}
public static class Defaults {
    public static class Preferences {
        public static int Text_cps = 28;
        public static int Afm_time = 8;
        public static bool Chaos_on = false;
    }
    public static bool Choice_1_new = true;
    public static bool Choice_2_new = true;
    public static bool Choice_3_new = true;
    public static bool Choice_1_newa = true;
    public static bool Choice_2_newa = true;
    public static bool Choice_3_newa = true;
    public static bool Choice_1_newb = true;
    public static class Persistent {
        public static int Gallery_fanwai1_lock = 0;
        public static int Gallery_fanwai2_lock = 0;
        public static int Gallery_fanwai3_lock = 0;
        public static int He_ending = 0;
        public static int Gallery_js_lock = 0;
        public static int Nvl_tran = 0;
        public static int Jq_1_1 = 0;
        public static int Jq_1_2 = 0;
        public static int Jq_1_3 = 0;
        public static int Jq_1_4 = 0;
        public static int Jq_1_5 = 0;
        public static int Jq_1_6 = 0;
        public static int Jq_2_1 = 0;
        public static int Jq_2_2 = 0;
        public static int Jq_2_3 = 0;
        public static int Jq_2_4 = 0;
        public static int Jq_2_5 = 0;
        public static int Jq_2_6 = 0;
        public static int Jq_2_7 = 0;
        public static int Jq_3_1 = 0;
        public static int Jq_3_2 = 0;
        public static int Jq_3_3 = 0;
        public static int Jq_3_4 = 0;
        public static int Jq_3_5 = 0;
        public static int Jq_3_6 = 0;
        public static int Jq_3_7 = 0;
        public static int Jq_4_1 = 0;
        public static int Jq_4_2 = 0;
        public static int Jq_4_3 = 0;
        public static int Jq_4_4 = 0;
        public static int Jq_5_1 = 0;
        public static int Jq_5_2 = 0;
        public static int Jq_5_3 = 0;
        public static int Jq_5_4 = 0;
        public static int Jq_5_5 = 0;
        public static int Jq_5_6 = 0;
        public static int Jq_5_7 = 0;
        public static int Jq_5_8 = 0;
        public static int Jq_6_1 = 0;
        public static int Jq_6_2 = 0;
        public static int Jq_6_3 = 0;
        public static int Jq_6_4 = 0;
        public static int Jq_6_5 = 0;
        public static int Jq_6_6 = 0;
        public static int Jq_6_7 = 0;
        public static int Jq_7_1 = 0;
        public static int Jq_7_2 = 0;
        public static int Jq_7_3 = 0;
        public static int Jq_7_4 = 0;
        public static int Jq_7_5 = 0;
        public static int Jq_7_6 = 0;
        public static int Jq_7_7 = 0;
        public static int Jq_7_8 = 0;
        public static int Jq_8_1 = 0;
        public static int Jq_8_2 = 0;
        public static int Jq_8_3 = 0;
        public static int Jq_8_4 = 0;
        public static int Jq_8_5 = 0;
        public static int Jq_8_6 = 0;
        public static int Jq_8_7 = 0;
        public static int Jq_8_8 = 0;
        public static int Jq_9_1 = 0;
        public static int Jq_9_2 = 0;
        public static int Jq_9_3 = 0;
        public static int Jq_9_4 = 0;
        public static int Jq_9_5 = 0;
        public static int Jq_9_6 = 0;
        public static int Jq_10_1 = 0;
        public static int Jq_10_2 = 0;
        public static int Jq_10_3 = 0;
        public static int Jq_10_4 = 0;
        public static int Jq_10_5 = 0;
        public static int Jq_10_6 = 0;
        public static int Jq_10_7 = 0;
        public static int Jq_10_8 = 0;
        public static int Jq_10_9 = 0;
        public static int Jq_10_10 = 0;
        public static int Jq_10_11 = 0;
        public static int Jq_11_1 = 0;
        public static int Jq_11_2 = 0;
        public static int Jq_11_3 = 0;
        public static int Jq_11_4 = 0;
        public static int Jq_11_5 = 0;
        public static int Jq_11_6 = 0;
        public static int Jq_11_7 = 0;
        public static string Povname = @"";
        public static int Povnamelenth = 0;
    }
    public static int Haogandu_he = 0;
    public static int Haogandu_nuo = 0;
    public static int Haogandu_an = 100;
    public static int Bai_xin = 1;
    public static int Bai_kiss = 0;
    public static int Bai_xue = 0;
    public static int Bai_bu = 0;
    public static int Bai_xiu = 0;
    public static int Bai_xinlai = 0;
    public static int He_xianzai = 0;
    public static int He_about_boyfriend = 0;
    public static int He_about_boyfriend_type = 0;
    public static int Wangzixian = 0;
    public static int Qigai = 0;
    public static int He_hen = 0;
    public static int Daan_1 = 0;
    public static int Gui_duihuakuang_you = 1;
    public static bool Quick_menu_none = false;
    public static bool Quick_menu = false;
}
public static class Engine {
    public static bool _dismiss_pause = false;
    public static bool _history = false;
}
public static class Voice_info {
    public static bool Sustain = false;
}